### ISSUE TITLE
Maven publication appears to contain no JARs

### ISSUE THREAD

**Issue by mikehearn** [ajalt/colormath#13]
See https://repo1.maven.org/maven2/com/github/ajalt/colormath/colormath/2.0.0/

**Comment by ajalt** [comment]
That link has all jars and expected files for me. Maybe maven had a service blip?

**Comment by mikehearn** [comment]
It's still broken for me. Is there a broken Maven Central mirror, maybe? This is what I see:

![image](https://user-images.githubusercontent.com/971089/113757005-64b94100-9712-11eb-8c10-7da4354e1893.png)

The Sonatype CDN is handled by Fastly so that would be concerning if so. `repo1.maven.org` currently resolves to `151.101.240.209` for me - what does it resolve to for you?
