### ISSUE TITLE
Enable the new IR compiler backend  for JS artifacts.

### ISSUE THREAD

**Issue by sureshg** [ajalt/colormath#14]
Right now colormath (`implementation("com.github.ajalt.colormath:colormath:2.0.0")`) library can't use in Kotlin/JS (`kotlin("js") version "1.5.0-RC"`) project, which throws the following error on compilation.

```kotlin
  > Could not resolve com.github.ajalt.colormath:colormath:2.0.0.
     Required by:
         project :
      > No matching variant of com.github.ajalt.colormath:colormath:2.0.0 was found. The consumer was configured to find a usage of 'kotlin-runtime' of a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'js', attribute 'org.jetbrains.kotlin.js.compiler' with value 'ir' but:
```

More info: https://kotlinlang.org/docs/js-ir-compiler.html#65018c1b

**Comment by ajalt** [comment]
I'll add IR artifacts to the next version. In the meantime, you may be able to configure your project to use the LEGACY compiler with `js(LEGACY)` if you don't have any IR-only dependencies.

**Comment by sureshg** [comment]
Thanks! Yeah, I will wait for the next version as I do have a few IR-only dependencies in my kotlin/js app.

**Comment by ajalt** [comment]
@sureshg FYI version 2.1.0 has been released with JS IR support
