### ISSUE TITLE
Make Jetpack Compose extension multiplatform

### ISSUE THREAD

**Issue by jakobkmar** [ajalt/colormath#27]
The Jetpack Compose extension seems to be Android only at the moment,
but Compose `Color` is actually multiplatform and defined in the commonMain part of `compose.ui.graphics`.

Therefore I don't see the need for this extension to be Android only here.
Making it multiplatform would allow the extension to be used for compose-jb as well.

Thanks in advance!

**Comment by ajalt** [comment]
That's a good idea. I'd welcome a PR.
