### ISSUE TITLE
Extensions Gradle declarations incorrect in docs

### ISSUE THREAD

**Issue by sebj** [ajalt/colormath#38]
The Gradle declarations for extensions in the documentation appear to be incorrect/outdated.

They all have the prefix `com.github.ajalt.colormath.extensions.colormath-ext-...`,  but the available Maven artifacts I can see have the prefix `com.github.ajalt.colormath.colormath-ext...`.

I initially copy-pasted from the docs and was puzzled as to why the dependency couldn't be resolved, before checking and realising this.

**Comment by ajalt** [comment]
Thanks for letting me know!
