### ISSUE TITLE
Add additional compile targets 

### ISSUE THREAD

**Issue by LaylaMeower** [ajalt/colormath#42]
Those being: `linuxArm64`, `wasm`.

In addition, what kinds of `tvos`, `watchos` and `ios` are you compiling to? Each has three variations: `X64`, `Arm64`, and `Simulator64`.

It would be lovely if you'll be able to add those compilation targets. Thanks anyway!

Oh, I see you're already working on Wasm at #41 😅

**Comment by ajalt** [comment]
You can look at the [maven repo to see] that i'm publishing all of the `*os` variants.

I added `linuxArm64`, give the snapshot a try and if it works I'll make a release.

[1]: https://repo1.maven.org/maven2/com/github/ajalt/colormath/

**Comment by LaylaMeower** [comment]
I'm working on the gradle right now, actually. I'll check it now, thanks!

**Comment by LaylaMeower** [comment]
It does work, yes.

**Comment by LaylaMeower** [comment]
@ajalt thought I might ping you on this. Can you release it anytime soon please? Thanks.

**Comment by ajalt** [comment]
@LaylaMeower done!

**Comment by LaylaMeower** [comment]
@ajalt Thanks! Will update!
