### ISSUE TITLE
Add wasm support

### ISSUE THREAD

**Issue by sgopi93** [ajalt/colormath#48]
It would be better if we add wasm support

**Comment by ajalt** [comment]
#41 is already open as an attempt to add it, but it's not currently possible since kotest doesn't support wasm, and that probably won't happen until kotlinx coroutines does.

**Comment by ajalt** [comment]
FYI https://github.com/kotest/kotest/issues/3598 is the kotest issue tracking wasm support. kotlinx.coroutines is has a PR open for wasm, so I expect we'll be able to add this soon.

**Comment by sgopi93** [comment]
Hi @ajalt , as coroutine 1.8.0-RC released with wasm. Can we add support now.

**Comment by ajalt** [comment]
I released 3.3.0  with a `wasmJs` target

**Comment by mikepenz** [comment]
Thank you so much @ajalt
