### ISSUE TITLE
About commonMain

### ISSUE THREAD

**Issue by AdamBoyleSignpostr** [ajalt/colormath#49]
I am trying to use the library in commonMain along with Jetpack Compose multiplaform.  However, I cannot implement the library, and can only implement in each platform, so I cannot use in commonMain.

**Comment by ajalt** [comment]
Here's the [list of targets colormath supports][1], although I'm planning on adding more soon. You can read up [on how kotlin structures in multiplatform targets][2] if you're having trouble using it.

[1]: https://github.com/ajalt/colormath#multiplatform
[2]: https://kotlinlang.org/docs/multiplatform-discover-project.html
