### ISSUE TITLE
Maybe make library JSR 363 compliant?

### ISSUE THREAD

**Issue by LouizFC** [ajalt/colormath#5]
I do alot of pixel and color manipulation and recently I began to use the Units of Measurement API for converting PDF dpi scales.

Maybe it would be useful to make the units of this library compliant to the JSR 275.

I fully understand that this is probably out of the scope of colormath, feel free to close it if wanted.

Thank you very much for your work on this lib.

**Comment by ajalt** [comment]
I'm not familiar with that JSR, but it looks like it was rejected? Can you provide more information on your use case?

**Comment by LouizFC** [comment]
Sorry, I got the number of the JSR wrong. I will try to spin an example

**Comment by LouizFC** [comment]
I am closing this for now. The "Units of Measurement" JSR  is way to complex to implement for the use case that I am thinking. It is better to just create another library instead of "polluting" this one with all the JSR boilerplate. I will try to create a working prototype and publish it to github when I get some free time.
