### ISSUE TITLE
[Color Space Request] HSLuv

### ISSUE THREAD

**Issue by dector** [ajalt/colormath#8]
> HSLuv is a human-friendly alternative to HSL.
>
> Here you can see CIELUV, a color space designed for perceptual uniformity based on human experiments. When accessed by polar coordinates, it becomes functionally similar to HSL with a single problem: its chroma component doesn't fit into a specific range.
> 
> HSLuv extends CIELUV with a new saturation component that allows you to span all the available chroma as a neat percentage.

— from [website](https://www.hsluv.org/)

**Comment by ajalt** [comment]
That's doable. XYZ is already implemented, but we'd still need LUV first. I'd definitely accept a PR.

Out of curiosity, what's your use case for HSLuv? I'm not familiar with that color space.

**Comment by dector** [comment]
> I'd definitely accept a PR.

Awesome! Can't promise it in the nearest times but will do.

> Out of curiosity, what's your use case for HSLuv?

Nothing particular TBH. But I like HSLuv more than usual HSL because of it's human-oriented nature.
Especially, I find Hue-transitions in HSLuv more smooth.

Here are nice comparisons: [boop](https://www.hsluv.org/comparison/). Check-out "Lightness" section and demo in the bottom.
